### ISSUE TITLE
First error code 2

### ISSUE THREAD

**Issue by biopsin** [magiclen/FFmpeg-Screen-Recorder#1]
Hi, just stumbled in here and wanted to testing the v1.0.18 release and it seems Im missing some other dependecy?

$ ./ffmpeg-screen-recorder -o /home/userx/Downloads/out.mkv
`Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }`

voidlinux_5.10_161-glibc

**Comment by magiclen** [comment]
Have you set up FFmpeg? If you don't add `ffmpeg` to your `$PATH`, you can use the `-f` option in the command to assign the path of FFmpeg executable.

You also need to make sure `xrandr` is available.

**Comment by biopsin** [comment]
`You also need to make sure xrandr is available.`
Yep that was it I only use the libXrandr not the interface.
